import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Container from '@/components/Container/Container';
import SideBar from '@/components/SideBar/SideBar';

import '../styles/globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <SideBar />
      <Container>{children}</Container>
    </body>
  </html>
);

export default RootLayout;
